baseURL: /
languageCode: en-us
title: Doni Halim's Blog

disableKinds:
  - taxonomy
  - term
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: Doni Halim
  description: Consider this as my online identity.

menu:
  main:
    - name: Home
      url: "/"
      weight: 1

    - name: About
      url: "/about"
      weight: 2

    - name: Feed
      url: "/index.xml"
      weight: 3
